default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payout_management_development

test:
  <<: *default
  database: payout_management_test

production:
  <<: *default
  database: payout_management_production
  username: payout_management
  password: <%= ENV["PAYOUT_MANAGEMENT_DATABASE_PASSWORD"] %>
